In [5]:
import numpy as np

Samples3D = np.ndarray # rows are samples, columns - x, y, z 


def sample_unit_sphere(npoints: int) -> Samples3D:
    ndim = 3
    vec = np.random.randn(ndim, npoints)
    vec /= np.linalg.norm(vec, axis=0)
    return vec.T

In [23]:
def uniform_3d_samples(npoints: int) -> Samples3D:
    ndim = 3
    return np.random.randn(ndim, npoints).T

In [7]:
sample_unit_sphere(10)

array([[-0.09538149, -0.79358754, -0.60093359],
       [ 0.85181805, -0.04172811,  0.52217313],
       [-0.60404173,  0.63706545, -0.47883316],
       [ 0.78033708,  0.59989158, -0.17664692],
       [ 0.30422927,  0.82127015, -0.48265919],
       [ 0.05116614, -0.96768959, -0.24689852],
       [-0.8259531 , -0.1767017 ,  0.53532979],
       [ 0.82073602, -0.43855531, -0.36614427],
       [-0.54481887, -0.8240459 , -0.15530858],
       [-0.98326205,  0.13607881,  0.12115405]])

In [24]:
uniform_3d_samples(10)

array([[ 2.76393456e-01,  1.72498828e+00, -2.27503188e+00],
       [-1.14858688e+00, -1.43718710e+00, -2.09980569e-03],
       [ 9.35816095e-01,  2.87501152e-03, -4.03953463e-03],
       [ 1.10402894e+00,  8.62517645e-01, -2.23661906e+00],
       [ 6.16701775e-02, -2.68824994e-01,  4.31143823e-01],
       [-2.14009510e+00,  3.03271663e-01,  3.47890966e-01],
       [ 5.83453400e-01,  1.83241088e+00, -1.18328519e+00],
       [-1.15704643e+00, -1.10263009e+00, -7.96880468e-01],
       [ 2.00537833e-01, -4.23827020e-02,  7.47356127e-01],
       [-4.51634147e-01,  1.27147189e+00,  2.61814660e-01]])

In [15]:
Mask3D = np.ndarray  # A boolean array representing a mask. Shape as in Samples3D


def constraints(arr: Samples3D) -> Mask3D:
    """ |x| >= |z| and |y| >= |z| """
    x, y, z = arr[:, 0], arr[:, 1], arr[:, 2]
    mask = np.logical_and(np.abs(x) >= np.abs(z), np.abs(y) >= np.abs(z))
    return mask

In [16]:
constraints(sample_unit_sphere(10))

array([ True, False,  True,  True, False, False, False, False, False,
       False])

In [17]:
a = sample_unit_sphere(10)
print(a)

c = constraints(a)
print(c)

print()
print(a[c])

[[-0.34018505  0.68153926  0.64790305]
 [-0.14970856  0.8741025   0.46209541]
 [-0.3939928   0.69111919 -0.60590753]
 [ 0.23674422 -0.9404402   0.24397623]
 [-0.1354907  -0.40632428  0.90362761]
 [-0.84639224 -0.4689849  -0.25233576]
 [ 0.05504609  0.80818724  0.58634744]
 [-0.04985157  0.99359881 -0.10137171]
 [-0.94622201 -0.07535082 -0.31462067]
 [ 0.45281919  0.67198555  0.58599505]]
[False False False False False  True False False False False]

[[-0.84639224 -0.4689849  -0.25233576]]


In [18]:
sphere_samples = sample_unit_sphere(1_000)
sphere_constraint_mask = constraints(sphere_samples)

sphere_feasible_set = sphere_samples[sphere_constraint_mask]
print(sphere_feasible_set.shape)

(321, 3)


In [22]:
import csv

with open("feasible_set_3d.csv", "w") as f:
    writer = csv.DictWriter(f, fieldnames=["x", "y", "z"])
    for sample in list(feasible_set):
        writer.writerow({"x": sample[0], "y": sample[1], "z": sample[2]})

In [25]:
uniform_samples = uniform_3d_samples(1_000)
uniform_constraint_mask = constraints(uniform_samples)

uniform_feasible_set = uniform_samples[uniform_constraint_mask]
print(uniform_feasible_set.shape)

(328, 3)


In [26]:
with open("uniform_feasible_set_3d.csv", "w") as f:
    writer = csv.DictWriter(f, fieldnames=["x", "y", "z"])
    writer.writeheader()
    for sample in list(uniform_feasible_set):
        writer.writerow({"x": sample[0], "y": sample[1], "z": sample[2]})